# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: 'windows-2019'
    steps:
    - task: WindowsMachineFileCopy@2
      inputs:
        SourcePath: '$(Build.Repository.LocalPath)\docker-compose.yaml'
        MachineNames: '13.91.227.5'
        AdminUserName: 'gshah'
        AdminPassword: '$WINPASS'
        TargetPath: '\\test'