apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: schoolofdevopsalbumviewer 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: schoolofdevopsalbumviewer 
    spec:
      containers:
        - name: schoolofdevopsalbumviewer 
          image: sofdreg.azurecr.io/schoolofdevopsalbumviewer
          ports:
          - containerPort: 80