apiVersion : apps/v1
kind: Deployment
metadata:
  name: schoolofdevopsalbumviewer 
spec:
  replicas: 1
  selector: 
    matchLabels: 
      app: schoolofdevopsalbumviewer
  template:
    metadata:
      labels:
        app: schoolofdevopsalbumviewer 
    spec:
      containers:
        - name: schoolofdevopsalbumviewer 
          image: sofdreg.azurecr.io/schoolofdevops/albumviewer
          ports:
          - containerPort: 80
          env: 
          - key: Data:Provider
            value: MySQL
          - key: Data:ConnectionString
            value: Server=database;Port=4000;Database=AlbumViewer;User=root;SslMode=None